### ISSUE TITLE
Basis installatie sveltekit

### ISSUE THREAD

**Issue by RubenErhardt** [annelinderaadsheer/lose-your-head-the-client-case#1]
Zorgen dat sveltekit werkt en is opgezet, en de wordpress API koppelen.

**Comment by Shannafdnd** [comment]
Sveltekit + Wordpress API is opgestart door: 
```
npm install --save wpapi
npm run dev
```

Wordpress API is gekoppeld door: 
```js
import { PUBLIC_APIURL } from '$env/static/public';
import WPAPI from 'wpapi';

const wp = new WPAPI({
	endpoint: PUBLIC_APIURL
});

export default wp
```
In het .env bestand staat: 
``` PUBLIC_APIURL = https://redpers.nl/wp-json ```

In elke route zit een +page.js bestand waar dit in staat:
```js
/** @type {import('./$types').PageLoad} */
import wp from "$lib/wordpress";

export async function load({ params }) {
    return {
        posts: await wp.posts().slug(params.slug)
    }
}
```

BRONNEN: 
- https://www.npmjs.com/package/wpapi
