### ISSUE TITLE
Global css aanmaken en basis custom properties erin zetten (Kleuren, px, borders)

### ISSUE THREAD

**Issue by RubenErhardt** [annelinderaadsheer/lose-your-head-the-client-case#10]
De opdrachtgever wilt een makkelijk te onderhouden pagina, dus veel met variabelen werken.

**Comment by Shannafdnd** [comment]
De Global.css is gelinkt door layout.svelte. Layout.svelte is een bestand dat werkt als een global.css, waar je bijv je nav in kan zetten, en dan zit het in elke pagina. Ik heb de global.css geimport in de layout.svelte. 
```js
<script>
	import '/global.css?url'
</script>

<slot></slot>
```

BRON:
- https://learn.svelte.dev/tutorial/layouts
