### ISSUE TITLE
Projectboard opzetten.

### ISSUE THREAD

**Issue by RubenErhardt** [annelinderaadsheer/lose-your-head-the-client-case#15]
Alle taken in het projectboard zetten, issues van maken, MOSCOW labels geven, pokerplanning maken en dlc labels geven.

**Comment by Shannafdnd** [comment]
**FEEDBACK**:
- testen meenemen in een pull request
- lisa, jason en yu jing hebben een checklist gevonden bij pull-requests
- iteraties is verwarrend en rommelig, die moeten weg
- dlc labels mogen ook weg
- testen moet per component
- per component fluid design
- opschonen
- 1 taal gebruiken
