### ISSUE TITLE
Datamodel Red Pers Begrijpen (Sitemap)

### ISSUE THREAD

**Issue by RubenErhardt** [annelinderaadsheer/lose-your-head-the-client-case#18]
Wij hebben al een API gekregen van onze opdrachtgever. Dus moeten wij reverse engineren. Wij moeten gaan begrijpen hoe de API werkt van Red Pers zodat we makkelijker te werk kunnen gaan.

**Comment by annelinderaadsheer** [comment]
https://mermaid.live/edit#pako:eNpVjr2OwkAMhF_FcsVJ5AVSIB3JQYMEEnRZCitxsivYHzkbIZTk3W9DmjtX9sw3I49Y-4Yxx_bpX7UmiXArlYM031WhxfTRUn-HLNtNR45gveP3BPvN0UOvfQjGdV8rv18gKMbTgjFEbdxjXq3ikz87nqCsThSiD_e_zu3lJ_ipzEWn-v-OFk6pQ9VS3lJWk0BB8kFwi5bFkmnS--OiKIyaLSvM09qQPBQqNyeOhuivb1djHmXgLYofOo2p8NmnawgNRS4NdUJ2ReZfufpaQg
