### ISSUE TITLE
Ontwerp Figma

### ISSUE THREAD

**Issue by RubenErhardt** [annelinderaadsheer/lose-your-head-the-client-case#35]

**Comment by RubenErhardt** [comment]
https://www.figma.com/design/YuHrvCKoPooq0q8WJsjh98/Red-Pers-web-24-25-v1.0.001-20240923?node-id=1-3&node-type=canvas&t=4YY080X4qhS9F3Xa-0

**Comment by annelinderaadsheer** [comment]
https://www.figma.com/design/jyzWjDVAPu2BI6jJPtBT6a/Red-Pers-web-24-25-v1.1.001-20240927?node-id=7-216&node-type=frame&t=RUKbppdLEYr060f9-0
