### ISSUE TITLE
Responsive | mobile |

### ISSUE THREAD

**Issue by RukiyaTossou** [annelinderaadsheer/lose-your-head-the-client-case#49]
De pagina is responsive. De pagina ziet er goed uit bij de mobile versie behalve de de images. 

De afbeelding is niet volledig in beeld.
![image](https://github.com/user-attachments/assets/1f8ad6c4-1fe7-45ad-a1b4-390c1c1e6e94)

**Comment by RubenErhardt** [comment]
De ims zijn nu responsive

```css
img{
max-width:100%;
height: auto;
```

![Screenshot 2024-10-08 210107](https://github.com/user-attachments/assets/bf2618d2-8a14-4f48-a4bb-f78cb3a024c6)
