### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by Naddybs** [annelinderaadsheer/lose-your-head-the-client-case#50]
<img width="900" alt="Scherm­afbeelding 2024-10-04 om 15 52 09" src="https://github.com/user-attachments/assets/8614cb8d-7dec-4849-9ff2-12cc6ff6b377">

Momenteel zijn de afbeeldingen niet responsive, waardoor ze de breedte van de body overschrijden. Voeg css toe om ervoor te zorgen dat de afbeeldingen zich aanpassen aan de breedte van hun container. Dit zorgt voor een betere gebruikerservaring op mobiele apparaten en tablets.

**Comment by RubenErhardt** [comment]
Ik heb de imgs responsive gemaakt. 

```CSS
  img {
    max-width: 100%;
    height: auto;
}
```

![Image](https://github.com/user-attachments/assets/28870980-138e-459d-b494-00d9d961e966)
