### ISSUE TITLE
Site live zetten

### ISSUE THREAD

**Issue by Shannafdnd** [annelinderaadsheer/lose-your-head-the-client-case#62]

**Comment by annelinderaadsheer** [comment]
**Error tijdens live zetten:**

![Image](https://github.com/user-attachments/assets/bead9b48-1260-4c51-be47-49a5f13588d9)

**Comment by annelinderaadsheer** [comment]
**Error opgelost:**

footer.svelte moest naar Footer.svelte veranderd worden.

**Live link:** https://lose-your-head-the-client-case-iu4t.vercel.app
