### ISSUE TITLE
Lighthouse test: hele artikel pagina

### ISSUE THREAD

**Issue by annelinderaadsheer** [annelinderaadsheer/lose-your-head-the-client-case#69]

**Comment by annelinderaadsheer** [comment]
**Desktop:**
![Image](https://github.com/user-attachments/assets/4536d6d8-b80e-4390-b4e1-0e846b818849)

**Mobile:**
![Image](https://github.com/user-attachments/assets/f7f0d9a3-8d41-4a05-b5bd-8abe4ed4fc99)

**Comment by Shannafdnd** [comment]
Ik heb een lighthouse test gedaan op de live versie van de website. Wat mij opviel is dat de performance beter is op de live versie, maar de accessibility op beide versies 70 procent is en een stuk beter zou kunnen. 

<h2>Mobile</h2>

![Image](https://github.com/user-attachments/assets/18b5f5d5-4e6c-48eb-90e1-bcc0a82ae84c)
![Image](https://github.com/user-attachments/assets/b348d935-3d08-49e4-a1a4-f00a95ddb338)
![Image](https://github.com/user-attachments/assets/6712db89-0d77-4f41-b658-d67678287310)
![Image](https://github.com/user-attachments/assets/1023db5e-8a92-4c25-986f-900a9b31e5d0)


<h2> Desktop </h2>

![Image](https://github.com/user-attachments/assets/1ac6e90e-47e1-4fa3-ab8f-cca6b000c726)
![Image](https://github.com/user-attachments/assets/60450c97-ea97-484b-8853-5d6f45b814f6)
![Image](https://github.com/user-attachments/assets/503b4b2f-9f63-418c-ace3-a04ef980cc44)
![Image](https://github.com/user-attachments/assets/b7e52d15-7e00-46c9-ac6c-dcc320d55b00)
